In [204]:
import pandas as pd
import numpy as np
import seaborn as sns
from datetime import datetime as dt

In [205]:
data = pd.read_csv('../goodtrainbadtrain/data/data_for_model.csv')
journeys = pd.read_csv('../goodtrainbadtrain/data/journeyindex.csv')

In [11]:
with pd.option_context("display.max_rows", 100, "display.max_columns", None):
    display(journeys)

,Unnamed: 0,date,weekday,month,journey_origin,journey_destination,journey_start,journey_end,journey_duration,journey_numberlegs,leg1_train,leg1_origin,leg1_destination,leg1_start,leg1_end,leg1_duration,leg2_train,leg2_origin,leg2_destination,leg2_start,leg2_end,leg2_duration,leg3_train,leg3_origin,leg3_destination,leg3_start,leg3_end,leg3_duration
0,0,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 04:22:00+02:00,2022-09-04 09:13:00+02:00,17460,2,ICE 521,Köln Hbf,Frankfurt(Main) Flughafen Fernbf,2022-09-04 04:22:00+02:00,2022-09-04 05:26:00+02:00,3840,railje63,Frankfurt(Main) Flughafen Fernbf,München Hbf,2022-09-04 05:39:00+02:00,2022-09-04 09:13:00+02:00,12840,-1,-1,-1,-1,-1,-1
1,1,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 04:22:00+02:00,2022-09-04 09:39:00+02:00,19020,1,ICE 521,Köln Hbf,München Hbf,2022-09-04 04:22:00+02:00,2022-09-04 09:39:00+02:00,19020,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,2,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 05:48:00+02:00,2022-09-04 10:27:00+02:00,16740,1,ICE 511,Köln Hbf,München Hbf,2022-09-04 05:48:00+02:00,2022-09-04 10:27:00+02:00,16740,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,3,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 06:54:00+02:00,2022-09-04 11:27:00+02:00,16380,2,ICE 101,Köln Hbf,Mannheim Hbf,2022-09-04 06:54:00+02:00,2022-09-04 08:23:00+02:00,5340,ICE 591,Mannheim Hbf,München Hbf,2022-09-04 08:30:00+02:00,2022-09-04 11:27:00+02:00,10620,-1,-1,-1,-1,-1,-1
4,4,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 07:55:00+02:00,2022-09-04 12:27:00+02:00,16320,1,ICE 513,Köln Hbf,München Hbf,2022-09-04 07:55:00+02:00,2022-09-04 12:27:00+02:00,16320,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,307,2022-09-10,5,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 18:27:00+02:00,2022-09-10 23:21:00+02:00,17640,3,ICE 590,München Hbf,Mannheim Hbf,2022-09-10 18:27:00+02:00,2022-09-10 21:29:00+02:00,10920,ICE 100,Mannheim Hbf,Köln Hbf,2022-09-10 21:36:00+02:00,Köln Hbf,5280,NaN,Köln Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 23:04:00+02:00,2022-09-10 23:21:00+02:00,1020
969,308,2022-09-10,5,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 19:28:00+02:00,2022-09-11 00:23:00+02:00,17700,2,ICE 510,München Hbf,Köln Hbf,2022-09-10 19:28:00+02:00,2022-09-11 00:06:00+02:00,16680,NaN,Köln Hbf,Köln Messe/Deutz Gl.11-12,2022-09-11 00:06:00+02:00,2022-09-11 00:23:00+02:00,1020,-1,-1,-1,-1,-1,-1
970,309,2022-09-11,6,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-11 00:01:00+02:00,2022-09-11 06:20:00+02:00,22740,2,ICE 618,München Hbf,Köln Hbf,2022-09-11 00:01:00+02:00,2022-09-11 06:03:00+02:00,21720,NaN,Köln Hbf,Köln Messe/Deutz Gl.11-12,2022-09-11 06:03:00+02:00,2022-09-11 06:20:00+02:00,1020,-1,-1,-1,-1,-1,-1
971,310,2022-09-11,6,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-11 03:24:00+02:00,2022-09-11 08:22:00+02:00,17880,2,ICE 616,München Hbf,Köln Hbf,2022-09-11 03:24:00+02:00,2022-09-11 08:05:00+02:00,16860,NaN,Köln Hbf,Köln Messe/Deutz Gl.11-12,2022-09-11 08:05:00+02:00,2022-09-11 08:22:00+02:00,1020,-1,-1,-1,-1,-1,-1
972,311,2022-09-11,6,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-11 05:33:00+02:00,2022-09-11 10:21:00+02:00,17280,2,ICE 614,München Hbf,Köln Hbf,2022-09-11 05:33:00+02:00,2022-09-11 10:04:00+02:00,16260,NaN,Köln Hbf,Köln Messe/Deutz Gl.11-12,2022-09-11 10:04:00+02:00,2022-09-11 10:21:00+02:00,1020,-1,-1,-1,-1,-1,-1

In [70]:
journeys = journeys[journeys.leg2_train.notna()]
journeys.shape

(930, 28)

In [78]:
journeys['key'] = list(range(journeys.shape[0]))

In [82]:
journeys.columns = ['Unnamed: 0', 'date', 'weekday', 'month', 'journey_origin',
       'journey_destination', 'journey_start', 'journey_end',
       'journey_duration', 'journey_numberlegs', 
       'train_leg1', 'origin_leg1','destination_leg1', 'start_leg1', 'end_leg1', 'duration_leg1',
       'train_leg2', 'origin_leg2', 'destination_leg2', 'start_leg2','end_leg2', 'duration_leg2', 
       'train_leg3', 'origin_leg3','destination_leg3', 'start_leg3', 'end_leg3', 'duration_leg3', 
       'index']

In [209]:

journeys = pd.read_csv('../goodtrainbadtrain/data/journeyindex.csv')

#processing
journeys = journeys[journeys.leg1_train.notna()] #delete duplicated trips that once go to köln hbf and once to deutz
journeys = journeys[journeys.leg2_train.notna()] 
journeys = journeys[journeys.leg3_train.notna()] 

journeys = journeys.drop(['Unnamed: 0'],axis=1) 
journeys['key_ID'] = list(range(journeys.shape[0]))

#rename columns (necessary for wide_to_long function)
journeys.columns = [ 'date', 'weekday', 'month', 'journey_origin',
       'journey_destination', 'journey_start', 'journey_end',
       'journey_duration', 'journey_numberlegs', 
       'train_leg1', 'origin_leg1','destination_leg1', 'start_leg1', 'end_leg1', 'duration_leg1',
       'train_leg2', 'origin_leg2', 'destination_leg2', 'start_leg2','end_leg2', 'duration_leg2', 
       'train_leg3', 'origin_leg3','destination_leg3', 'start_leg3', 'end_leg3', 'duration_leg3', 
       'key_ID']

journeys_long = pd.wide_to_long(df = journeys,
                                stubnames=['train', 'origin','destination', 'start', 'end', 'duration'],
                                i=['key_ID'],
                                j='leg',
                                sep = '_',
                                suffix='.+').reset_index()

#delete empty legs
journeys_long = journeys_long[journeys_long.train != '-1']

#reorder columns
journeys_long = journeys_long[['key_ID', 
 'journey_origin', 
 'journey_destination',
 'journey_start',
 'journey_end',
 'journey_duration', 
 'journey_numberlegs',
 'leg', 
 'train', 
 'origin', 
 'destination', 
 'start', 
 'end',
 'duration',
 'date', 'month','weekday']]


def date_transformation(df, columns):
    for col in columns:
        df[col] = df[col].str.split('+', expand=True)[[0]]
        df[col] = pd.to_datetime(df[col])
    return df


journeys_long = date_transformation(journeys_long, ['journey_start', 'journey_end']) #, 'start', 'end'])
journeys_long['month'] = journeys_long['journey_start'].dt.month_name()
journeys_long['weekday'] = journeys_long['journey_start'].dt.day_name()


simple_journeys = journeys[journeys.journey_numberlegs == 1]
simple_journeys_tomunich = simple_journeys[simple_journeys.journey_destination == "München Hbf"].train_leg1.unique()
simple_journeys_tocologne = simple_journeys[(simple_journeys.journey_destination == "Köln Hbf") | (simple_journeys.journey_destination == "Köln Messe/Deutz Gl.11-12")].train_leg1.unique()


data['ends_cologne'] = data['zugnr'].isin(simple_journeys_tocologne.tolist())
data['ends_munich'] = data['zugnr'].isin(simple_journeys_tomunich.tolist())


cologne_mask = (data.ends_cologne) & (data.city == 'Köln')
munich_mask = (data.ends_munich) & (data.city == 'München')
data = data[cologne_mask | munich_mask]

with pd.option_context("display.max_rows", 100, "display.max_columns", None):
    display(data)

data.to_csv('../goodtrainbadtrain/data/data_for_model_2.csv')
# check all legs of one journey (connected by key_ID)   
# with pd.option_context("display.max_rows", 100, "display.max_columns", None):
# display(journeys_long[journeys_long.key_ID == 0])

,Unnamed: 0,zugnr,datum,bhf,arrTime,adelay,depTime,ddelay,city,start_or_endpoint,arrTime_clean,depTime_clean,expected_atime,sharp_date,temp,prcp,snow,wspd,wpgt,coco,date,weekday,month,target,target_binary,target_numeric,hour,time_of_day,ends_cologne,ends_munich
8615,8615,ICE 512,2019-12-15,Köln Hbf,2205,0,9999,0,Köln,end,2205,2205,2019-12-15 22:05:00,2019-12-15 22:00:00,5.6,0.0,NaN,9.4,13.0,good,2019-12-15 22:05:00,Sunday,December,on time,1,0,1900-01-01 22:05:00,evening,True,False
8616,8616,ICE 512,2019-12-16,Köln Hbf,2205,34,9999,34,Köln,end,2205,2205,2019-12-16 22:05:00,2019-12-16 22:00:00,9.3,0.0,NaN,19.1,25.0,medium,2019-12-16 22:05:00,Monday,December,large delay/cancelled,0,34,1900-01-01 22:05:00,evening,True,False
8617,8617,ICE 512,2019-12-17,Köln Hbf,2205,21,9999,21,Köln,end,2205,2205,2019-12-17 22:05:00,2019-12-17 22:00:00,11.5,0.5,NaN,11.9,28.0,medium,2019-12-17 22:05:00,Tuesday,December,medium delay,0,21,1900-01-01 22:05:00,evening,True,False
8618,8618,ICE 512,2019-12-18,Köln Hbf,2205,2,9999,0,Köln,end,2205,2205,2019-12-18 22:05:00,2019-12-18 22:00:00,8.3,0.0,NaN,14.8,25.0,good,2019-12-18 22:05:00,Wednesday,December,small delay,0,2,1900-01-01 22:05:00,evening,True,False
8619,8619,ICE 512,2019-12-19,Köln Hbf,2205,10,9999,0,Köln,end,2205,2205,2019-12-19 22:05:00,2019-12-19 22:00:00,10.1,0.0,NaN,27.0,39.0,medium,2019-12-19 22:05:00,Thursday,December,medium delay,0,10,1900-01-01 22:05:00,evening,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130274,130274,NJ 421,2022-05-11,München Hbf,711,0,728,0,München,NaN,711,728,2022-05-11 07:11:00,2022-05-11 07:00:00,19.8,0.0,0.0,9.4,18.0,medium,2022-05-11 07:11:00,Wednesday,May,on time,1,0,1900-01-01 07:11:00,morning,False,True
130275,130275,NJ 421,2022-05-12,München Hbf,711,21,728,9,München,NaN,711,728,2022-05-12 07:11:00,2022-05-12 07:00:00,21.4,0.0,0.0,15.5,32.0,medium,2022-05-12 07:11:00,Thursday,May,medium delay,0,21,1900-01-01 07:11:00,morning,False,True
130276,130276,NJ 421,2022-05-13,München Hbf,711,0,728,5,München,NaN,711,728,2022-05-13 07:11:00,2022-05-13 07:00:00,15.8,0.7,0.0,5.8,12.0,bad,2022-05-13 07:11:00,Friday,May,on time,1,0,1900-01-01 07:11:00,morning,False,True
130277,130277,NJ 421,2022-05-14,München Hbf,711,0,728,0,München,NaN,711,728,2022-05-14 07:11:00,2022-05-14 07:00:00,15.4,0.0,0.0,2.2,5.0,medium,2022-05-14 07:11:00,Saturday,May,on time,1,0,1900-01-01 07:11:00,morning,False,True
130278,130278,NJ 421,2022-05-15,München Hbf,711,61,728,49,München,NaN,711,728,2022-05-15 07:11:00,2022-05-15 07:00:00,18.0,0.0,0.0,2.9,8.0,medium,2022-05-15 07:11:00,Sunday,May,large delay/cancelled,0,61,1900-01-01 07:11:00,morning,False,True

In [170]:
simple_journeys = journeys[journeys.journey_numberlegs == 1]

In [176]:
simple_journeys_tomunich = simple_journeys[simple_journeys.journey_destination == "München Hbf"].train_leg1.unique()
simple_journeys_tomunich

array(['ICE 521', 'ICE 511', 'ICE 513', 'ICE 515', 'ICE 517', 'ICE 519',
       'ICE 611', 'ICE 613', 'ICE 615', 'ICE 619', 'ICE 827', 'NJ 421',
       'ICE 525', 'ICE 527', 'ICE 529', 'ICE 621', 'ICE 623', 'ICE 625',
       'ICE 627', 'ICE 629', 'ICE 721', 'ICE 723', 'ICE 725', 'ICE 727',
       'ICE 729', 'ICE 821', 'ICE 523'], dtype=object)

In [183]:
simple_journeys_tocologne = simple_journeys[(simple_journeys.journey_destination == "Köln Hbf") | (simple_journeys.journey_destination == "Köln Messe/Deutz Gl.11-12")].train_leg1.unique()
simple_journeys_tocologne

array(['ICE 614', 'ICE 612', 'ICE 610', 'ICE 518', 'ICE 516', 'ICE 514',
       'IC 1910', 'ICE 512', 'ICE 522', 'ICE 510', 'ICE 618', 'ICE 616',
       'NJ 420', 'ICE 728', 'ICE 726', 'ICE 724', 'ICE 722', 'ICE 720',
       'ICE 628', 'ICE 626', 'ICE 624', 'ICE 622', 'ICE 620', 'ICE 528',
       'ICE 526', 'ICE 524', 'ICE 822', 'ICE 820'], dtype=object)

In [186]:
data.start_or_endpoint.value_counts()

end      36790
start    34059
Name: start_or_endpoint, dtype: int64

In [187]:
startend = data.start_or_endpoint

for index, row in data.iterrows():
    if row.city == 'Köln':
        if row.zugnr in simple_journeys_tocologne:
            startend[index] = "end"
    if row.city == 'München':
        if row.zugnr in simple_journeys_tomunich:
            startend[index] = "end"

startend.value_counts()

/var/folders/0v/92j280qj2j971syqfbthtx0r0000gn/T/ipykernel_19731/1128368728.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  startend[index] = "end"
/var/folders/0v/92j280qj2j971syqfbthtx0r0000gn/T/ipykernel_19731/1128368728.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  startend[index] = "end"

KeyboardInterrupt:

In [202]:
#data[data.zugnr  simple_journeys_tocologne.tolist()]
#data[data.zugnr in simple_journeys_tomunich]


data['ends_cologne'] = data['zugnr'].isin(simple_journeys_tocologne.tolist())
data['ends_munich'] = data['zugnr'].isin(simple_journeys_tomunich.tolist())

cologne_mask = (data.ends_cologne) & (data.city == 'Köln')
munich_mask = (data.ends_munich) & (data.city == 'München')
data = data[cologne_mask | munich_mask]
data.hea

(40079, 30)

In [199]:
cologne_mask

0         False
1         False
2         False
3         False
4         False
          ...
130274    False
130275    False
130276    False
130277    False
130278    False
Length: 130279, dtype: bool

In [185]:
data.head()

,Unnamed: 0,zugnr,datum,bhf,arrTime,adelay,depTime,ddelay,city,start_or_endpoint,...,wpgt,coco,date,weekday,month,target,target_binary,target_numeric,hour,time_of_day
0,0,EC 6,2019-12-15,Köln Hbf,1906,0,1908,0,Köln,NaN,...,21.0,medium,2019-12-15 19:06:00,Sunday,December,on time,1,0,1900-01-01 19:06:00,evening
1,1,EC 6,2019-12-16,Köln Hbf,1906,10,1909,8,Köln,NaN,...,18.0,medium,2019-12-16 19:06:00,Monday,December,medium delay,0,10,1900-01-01 19:06:00,evening
2,2,EC 6,2019-12-17,Köln Hbf,1906,47,1909,47,Köln,NaN,...,30.0,medium,2019-12-17 19:06:00,Tuesday,December,large delay/cancelled,0,47,1900-01-01 19:06:00,evening
3,3,EC 6,2019-12-18,Köln Hbf,1906,-1,1909,-1,Köln,NaN,...,28.0,good,2019-12-18 19:06:00,Wednesday,December,large delay/cancelled,0,120,1900-01-01 19:06:00,evening
4,4,EC 6,2019-12-18,Köln Messe/Deutz Gl.11-12,1906,29,1909,30,Köln,NaN,...,28.0,good,2019-12-18 19:06:00,Wednesday,December,medium delay,0,29,1900-01-01 19:06:00,evening

In [111]:
with pd.option_context("display.max_rows", 100, "display.max_columns", None):
    display(journeys_long[journeys_long.train == 'ICE 100'])

,key_ID,journey_origin,journey_destination,journey_start,journey_end,journey_duration,journey_numberlegs,leg,train,origin,destination,start,end,duration,date,month,weekday
1547,617,München Hbf,Köln Hbf,2022-09-09 18:27:00+02:00,2022-09-09 23:04:00+02:00,16620,2,leg2,ICE 100,Mannheim Hbf,Köln Hbf,2022-09-09 21:36:00+02:00,2022-09-09 23:04:00+02:00,5280,2022-09-09,9,4
1574,644,München Hbf,Köln Hbf,2022-09-10 18:27:00+02:00,2022-09-10 23:04:00+02:00,16620,2,leg2,ICE 100,Mannheim Hbf,Köln Hbf,2022-09-10 21:36:00+02:00,2022-09-10 23:04:00+02:00,5280,2022-09-10,9,5
1821,891,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-09 18:27:00+02:00,2022-09-09 23:21:00+02:00,17640,3,leg2,ICE 100,Mannheim Hbf,Köln Hbf,2022-09-09 21:36:00+02:00,Köln Hbf,5280,2022-09-09,9,4
1859,929,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 18:27:00+02:00,2022-09-10 23:21:00+02:00,17640,3,leg2,ICE 100,Mannheim Hbf,Köln Hbf,2022-09-10 21:36:00+02:00,Köln Hbf,5280,2022-09-10,9,5
2350,490,München Hbf,Köln Hbf,2022-09-04 18:16:00+02:00,2022-09-04 23:04:00+02:00,17280,3,leg3,ICE 100,Frankfurt(Main) Flughafen Fernbf,Köln Hbf,2022-09-04 22:09:00+02:00,2022-09-04 23:04:00+02:00,3300,2022-09-04,9,6
2375,515,München Hbf,Köln Hbf,2022-09-05 18:16:00+02:00,2022-09-05 23:04:00+02:00,17280,3,leg3,ICE 100,Frankfurt(Main) Flughafen Fernbf,Köln Hbf,2022-09-05 22:09:00+02:00,2022-09-05 23:04:00+02:00,3300,2022-09-05,9,0
2400,540,München Hbf,Köln Hbf,2022-09-06 18:16:00+02:00,2022-09-06 23:04:00+02:00,17280,3,leg3,ICE 100,Frankfurt(Main) Flughafen Fernbf,Köln Hbf,2022-09-06 22:09:00+02:00,2022-09-06 23:04:00+02:00,3300,2022-09-06,9,1
2425,565,München Hbf,Köln Hbf,2022-09-07 18:16:00+02:00,2022-09-07 23:04:00+02:00,17280,3,leg3,ICE 100,Frankfurt(Main) Flughafen Fernbf,Köln Hbf,2022-09-07 22:09:00+02:00,2022-09-07 23:04:00+02:00,3300,2022-09-07,9,2
2450,590,München Hbf,Köln Hbf,2022-09-08 18:16:00+02:00,2022-09-08 23:04:00+02:00,17280,3,leg3,ICE 100,Frankfurt(Main) Flughafen Fernbf,Köln Hbf,2022-09-08 22:09:00+02:00,2022-09-08 23:04:00+02:00,3300,2022-09-08,9,3

In [27]:
#divide simple and complex trips
simple_journeys = journeys[journeys.journey_numberlegs == 1]
complex_journeys = journeys[journeys.journey_numberlegs != 1]

with pd.option_context("display.max_rows", 10, "display.max_columns", None):
    display(simple_journeys)

,Unnamed: 0,date,weekday,month,journey_origin,journey_destination,journey_start,journey_end,journey_duration,journey_numberlegs,leg1_train,leg1_origin,leg1_destination,leg1_start,leg1_end,leg1_duration,leg2_train,leg2_origin,leg2_destination,leg2_start,leg2_end,leg2_duration,leg3_train,leg3_origin,leg3_destination,leg3_start,leg3_end,leg3_duration
1,1,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 04:22:00+02:00,2022-09-04 09:39:00+02:00,19020,1,ICE 521,Köln Hbf,München Hbf,2022-09-04 04:22:00+02:00,2022-09-04 09:39:00+02:00,19020,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,2,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 05:48:00+02:00,2022-09-04 10:27:00+02:00,16740,1,ICE 511,Köln Hbf,München Hbf,2022-09-04 05:48:00+02:00,2022-09-04 10:27:00+02:00,16740,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,4,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 07:55:00+02:00,2022-09-04 12:27:00+02:00,16320,1,ICE 513,Köln Hbf,München Hbf,2022-09-04 07:55:00+02:00,2022-09-04 12:27:00+02:00,16320,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
7,7,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 09:55:00+02:00,2022-09-04 14:27:00+02:00,16320,1,ICE 515,Köln Hbf,München Hbf,2022-09-04 09:55:00+02:00,2022-09-04 14:27:00+02:00,16320,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
10,10,2022-09-04,6,9,Köln Hbf,München Hbf,2022-09-04 11:55:00+02:00,2022-09-04 16:27:00+02:00,16320,1,ICE 517,Köln Hbf,München Hbf,2022-09-04 11:55:00+02:00,2022-09-04 16:27:00+02:00,16320,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954,293,2022-09-10,5,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 14:18:00+02:00,2022-09-10 19:15:00+02:00,17820,1,ICE 622,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 14:18:00+02:00,2022-09-10 19:15:00+02:00,17820,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
958,297,2022-09-10,5,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 15:25:00+02:00,2022-09-10 20:24:00+02:00,17940,1,ICE 620,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 15:25:00+02:00,2022-09-10 20:24:00+02:00,17940,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
960,299,2022-09-10,5,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 16:14:00+02:00,2022-09-10 21:14:00+02:00,18000,1,ICE 528,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 16:14:00+02:00,2022-09-10 21:14:00+02:00,18000,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
965,304,2022-09-10,5,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 17:19:00+02:00,2022-09-10 22:13:00+02:00,17640,1,ICE 526,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 17:19:00+02:00,2022-09-10 22:13:00+02:00,17640,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
967,306,2022-09-10,5,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 18:16:00+02:00,2022-09-10 23:36:00+02:00,19200,1,ICE 524,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 18:16:00+02:00,2022-09-10 23:36:00+02:00,19200,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [30]:
simple_journeys.shape #376 simple trips -> ca. 600 complex trips

(376, 28)

In [48]:
ices = simple_journeys.leg1_train.unique()
ices.size
ices

array(['ICE 521', 'ICE 511', 'ICE 513', 'ICE 515', 'ICE 517', 'ICE 519',
       'ICE 611', 'ICE 613', 'ICE 615', 'ICE 619', 'ICE 827', 'NJ 421',
       'ICE 525', 'ICE 527', 'ICE 529', 'ICE 621', 'ICE 623', 'ICE 625',
       'ICE 627', 'ICE 629', 'ICE 721', 'ICE 723', 'ICE 725', 'ICE 727',
       'ICE 729', 'ICE 821', 'ICE 523', 'ICE 614', 'ICE 612', 'ICE 610',
       'ICE 518', 'ICE 516', 'ICE 514', 'IC 1910', 'ICE 512', 'ICE 522',
       'ICE 510', 'ICE 618', 'ICE 616', 'NJ 420', 'ICE 728', 'ICE 726',
       'ICE 724', 'ICE 722', 'ICE 720', 'ICE 628', 'ICE 626', 'ICE 624',
       'ICE 622', 'ICE 620', 'ICE 528', 'ICE 526', 'ICE 524', 'ICE 822',
       'ICE 820'], dtype=object)

In [44]:
ices_history = data.zugnr.unique()
ices_history

array(['EC 6', 'EC 8', 'IC 2011', 'IC 2013', 'IC 2210', 'IC 2213',
       'IC 2216', 'IC 2312', 'IC 2319', 'ICE 100', 'ICE 101', 'ICE 102',
       'ICE 1020', 'ICE 1022', 'ICE 103', 'ICE 104', 'ICE 105', 'ICE 106',
       'ICE 107', 'ICE 108', 'ICE 109', 'ICE 1123', 'ICE 200', 'ICE 201',
       'ICE 202', 'ICE 203', 'ICE 204', 'ICE 22', 'ICE 23', 'ICE 26',
       'ICE 27', 'ICE 511', 'ICE 512', 'ICE 513', 'ICE 514', 'ICE 515',
       'ICE 516', 'ICE 517', 'ICE 518', 'ICE 519', 'ICE 521', 'ICE 522',
       'ICE 523', 'ICE 524', 'ICE 525', 'ICE 526', 'ICE 527', 'ICE 528',
       'ICE 529', 'ICE 610', 'ICE 611', 'ICE 612', 'ICE 613', 'ICE 614',
       'ICE 615', 'ICE 616', 'ICE 618', 'ICE 619', 'ICE 620', 'ICE 621',
       'ICE 622', 'ICE 623', 'ICE 624', 'ICE 625', 'ICE 626', 'ICE 627',
       'ICE 628', 'ICE 629', 'ICE 720', 'ICE 721', 'ICE 722', 'ICE 723',
       'ICE 724', 'ICE 725', 'ICE 726', 'ICE 727', 'ICE 728', 'ICE 729',
       'ICE 820', 'ICE 821', 'ICE 822', 'ICE 827', 'ICE 929', 'NJ 420',
       'NJ 421', 'IC 118', 'IC 119', 'ICE 1121', 'ICE 1122', 'ICE 206',
       'ICE 927', 'ICE 928', 'FLX 1358', 'IC 60403', 'ICE 1120',
       'ICE 1621', 'ICE 1627', 'ICE 228', 'ICE 229', 'ICE 28', 'ICE 29',
       'ICE 510', 'ICE 713', 'ICE 714', 'ICE 920', 'IC 2265', 'IC 2266',
       'IC 2269', 'ICE 1003', 'ICE 1004', 'ICE 1005', 'ICE 1006',
       'ICE 1007', 'ICE 1009', 'ICE 590', 'ICE 591', 'ICE 592', 'ICE 593',
       'ICE 594', 'ICE 595', 'ICE 596', 'ICE 597', 'ICE 598', 'ICE 599',
       'ICE 690', 'ICE 691', 'ICE 692', 'ICE 693', 'ICE 698', 'ICE 699',
       'ICE 707', 'ICE 800', 'ICE 886', 'ICE 888', 'ICE 1109'],
      dtype=object)

In [63]:
pd.Series(np.intersect1d(data.zugnr,simple_journeys.leg1_train)).size

54

In [66]:
#check for one train 
simple_journeys[simple_journeys.leg1_train == 'ICE 822']

,Unnamed: 0,date,weekday,month,journey_origin,journey_destination,journey_start,journey_end,journey_duration,journey_numberlegs,...,leg2_destination,leg2_start,leg2_end,leg2_duration,leg3_train,leg3_origin,leg3_destination,leg3_start,leg3_end,leg3_duration
702,41,2022-09-05,0,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-05 04:27:00+02:00,2022-09-05 09:15:00+02:00,17280,1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
747,86,2022-09-06,1,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-06 04:27:00+02:00,2022-09-06 09:15:00+02:00,17280,1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
792,131,2022-09-07,2,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-07 04:27:00+02:00,2022-09-07 09:15:00+02:00,17280,1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
837,176,2022-09-08,3,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-08 04:27:00+02:00,2022-09-08 09:15:00+02:00,17280,1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
882,221,2022-09-09,4,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-09 04:27:00+02:00,2022-09-09 09:15:00+02:00,17280,1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
929,268,2022-09-10,5,9,München Hbf,Köln Messe/Deutz Gl.11-12,2022-09-10 04:27:00+02:00,2022-09-10 09:15:00+02:00,17280,1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [65]:
data[data.zugnr == 'ICE 523']
#data[data.zugnr == 'ICE 728']

,Unnamed: 0,zugnr,datum,bhf,arrTime,adelay,depTime,ddelay,city,start_or_endpoint,...,wpgt,coco,date,weekday,month,target,target_binary,target_numeric,hour,time_of_day
11779,11779,ICE 523,2019-12-16,Köln Messe/Deutz Gl.11-12,518,0,520,2,Köln,NaN,...,28.0,medium,2019-12-16 05:18:00,Monday,December,on time,1,0,1900-01-01 05:18:00,night
11780,11780,ICE 523,2019-12-17,Köln Messe/Deutz Gl.11-12,518,0,520,2,Köln,NaN,...,15.0,medium,2019-12-17 05:18:00,Tuesday,December,on time,1,0,1900-01-01 05:18:00,night
11781,11781,ICE 523,2019-12-18,Köln Messe/Deutz Gl.11-12,518,0,520,1,Köln,NaN,...,9.0,medium,2019-12-18 05:18:00,Wednesday,December,on time,1,0,1900-01-01 05:18:00,night
11782,11782,ICE 523,2019-12-19,Köln Messe/Deutz Gl.11-12,518,0,520,2,Köln,NaN,...,28.0,medium,2019-12-19 05:18:00,Thursday,December,on time,1,0,1900-01-01 05:18:00,night
11783,11783,ICE 523,2019-12-20,Köln Messe/Deutz Gl.11-12,518,0,520,2,Köln,NaN,...,42.0,medium,2019-12-20 05:18:00,Friday,December,on time,1,0,1900-01-01 05:18:00,night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121035,121035,ICE 523,2022-05-12,München Hbf,1006,0,9999,0,München,end,...,41.0,medium,2022-05-12 10:06:00,Thursday,May,on time,1,0,1900-01-01 10:06:00,morning
121036,121036,ICE 523,2022-05-13,München Hbf,1006,26,9999,0,München,end,...,25.0,bad,2022-05-13 10:06:00,Friday,May,medium delay,0,26,1900-01-01 10:06:00,morning
121037,121037,ICE 523,2022-05-14,München Hbf,1006,2,9999,0,München,end,...,14.0,good,2022-05-14 10:06:00,Saturday,May,small delay,0,2,1900-01-01 10:06:00,morning
121038,121038,ICE 523,2022-05-15,München Hbf,1006,4,9999,0,München,end,...,21.0,good,2022-05-15 10:06:00,Sunday,May,small delay,0,4,1900-01-01 10:06:00,morning
121039,121039,ICE 523,2022-05-16,München Hbf,1006,2,9999,0,München,end,...,NaN,NaN,2022-05-16 10:06:00,Monday,May,small delay,0,2,1900-01-01 10:06:00,morning

In [60]:
simple_journeys.groupby('journey_duration').sum()

,Unnamed: 0,weekday,month,journey_numberlegs,leg1_duration,leg2_duration,leg3_duration
journey_duration,,,,,,,
16260,1346,48,135,15,243900,-15,-15
16320,2723,105,315,35,571200,-35,-35
16380,575,21,63,7,114660,-7,-7
16620,3115,105,315,35,581700,-35,-35
16680,709,21,63,7,116760,-7,-7
16740,649,27,72,8,133920,-8,-8
16800,678,21,63,7,117600,-7,-7
16860,731,21,63,7,118020,-7,-7
17160,952,21,63,7,120120,-7,-7
17280,2074,36,117,13,224640,-13,-13
17340,2131,42,126,14,242760,-14,-14
17400,992,21,63,7,121800,-7,-7
17520,2192,42,126,14,245280,-14,-14
17580,1110,21,63,7,123060,-7,-7
17640,4266,84,252,28,493920,-28,-28
17700,1020,21,63,7,123900,-7,-7
17760,1043,21,63,7,124320,-7,-7
17820,3206,63,189,21,374220,-21,-21
17940,4174,84,252,28,502320,-28,-28
18000,2125,42,126,14,252000,-14,-14
18060,1062,21,63,7,126420,-7,-7
18120,702,21,63,7,126840,-7,-7
18180,929,15,54,6,109080,-6,-6
18420,1034,21,63,7,128940,-7,-7
18540,1192,21,63,7,129780,-7,-7
18780,925,15,54,6,112680,-6,-6
18840,469,15,54,6,113040,-6,-6
19020,641,27,72,8,152160,-8,-8
19200,1198,21,63,7,134400,-7,-7
21720,724,21,63,7,152040,-7,-7
22080,625,21,63,7,154560,-7,-7
23160,16,6,9,1,23160,-1,-1
28860,1356,36,72,8,230880,-8,-8
32100,638,20,36,4,128400,-4,-4